spring:
  profiles:
    active: dev
  application:
    name: vet-clinic
  mvc:
    throw-exception-if-no-handler-found: true
  docker:
    compose:
      lifecycle-management: start_and_stop


springdoc:
  swagger-ui:
    path: /swagger
